sonar.organization=internxt
sonar.projectKey=internxt_mail-web
sonar.projectName=mail-web
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.json,**/assets/**,**/*.css
sonar.cpd.exclusions=**/*.json,**/assets/**,**/*.css