name: SonarCloud analysis

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci

      - name: Unit test run
        run: npm run test:coverage
        env:
          VITE_PAYMENTS_API_URL: ${{ secrets.PAYMENTS_API_URL }}
          VITE_DRIVE_API_URL: ${{ secrets.DRIVE_API_URL }}
          VITE_MAGIC_IV: ${{ secrets.MAGIC_IV }}
          VITE_MAGIC_SALT: ${{ secrets.MAGIC_SALT }}
          VITE_CRYPTO_SECRET: ${{ secrets.CRYPTO_SECRET }}
          VITE_DRIVE_APP_URL: ${{ secrets.DRIVE_APP_URL }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
